"""initial schema

Revision ID: 8db63466d0ac
Revises: 
Create Date: 2026-05-13 10:06:40.813119
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8db63466d0ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avocarbon_site',
    sa.Column('id_site', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.String(length=200), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_site', name=op.f('pk_avocarbon_site'))
    )
    op.create_table('pld_scoring_rules',
    sa.Column('rule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria_type', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('min_value', sa.String(length=255), nullable=True),
    sa.Column('max_value', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_pld_scoring_rules'))
    )
    op.create_table('supplier_group',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=200), nullable=True),
    sa.Column('supplier_scope', sa.String(length=20), nullable=True),
    sa.Column('strategique', sa.Boolean(), nullable=True),
    sa.Column('monopolistique', sa.Boolean(), nullable=True),
    sa.Column('multi_site', sa.Boolean(), nullable=True),
    sa.Column('directed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('exit_supplier', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('strategic_reason', sa.Text(), nullable=True),
    sa.Column('supplier_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_group', name=op.f('pk_supplier_group'))
    )
    op.create_table('supplier_unit',
    sa.Column('id_supplier_unit', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('supplier_code', sa.String(length=50), nullable=True),
    sa.Column('address_line', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('product_category', sa.String(length=255), nullable=True),
    sa.Column('amount_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_currency', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['supplier_group.id_group'], name=op.f('fk_supplier_unit_id_group_supplier_group'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_supplier_unit', name=op.f('pk_supplier_unit'))
    )
    op.create_table('contact',
    sa.Column('id_contact', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_label', sa.String(length=100), nullable=True),
    sa.Column('role_name', sa.String(length=150), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=True),
    sa.Column('id_supplier_group', sa.Integer(), nullable=True),
    sa.Column('id_supplier_unit', sa.Integer(), nullable=True),
    sa.Column('id_site', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_site'], ['avocarbon_site.id_site'], name=op.f('fk_contact_id_site_avocarbon_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_supplier_group'], ['supplier_group.id_group'], name=op.f('fk_contact_id_supplier_group_supplier_group'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_supplier_unit'], ['supplier_unit.id_supplier_unit'], name=op.f('fk_contact_id_supplier_unit_supplier_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_contact', name=op.f('pk_contact'))
    )
    op.create_table('opportunity',
    sa.Column('opportunity_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_name', sa.Text(), nullable=True),
    sa.Column('opportunity_type', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('idea_owner', sa.String(length=255), nullable=True),
    sa.Column('purchasing_owner', sa.String(length=255), nullable=True),
    sa.Column('project_owner', sa.String(length=255), nullable=True),
    sa.Column('conversion_owner', sa.String(length=255), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('expected_annual_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('real_start_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('results', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_year', sa.Numeric(precision=4, scale=0), nullable=True),
    sa.Column('phase_status', sa.String(length=255), nullable=True),
    sa.Column('validation_decision', sa.String(length=255), nullable=True),
    sa.Column('status2', sa.String(length=255), nullable=True),
    sa.Column('change_mode', sa.String(length=255), nullable=True),
    sa.Column('assumptions_summary', sa.Text(), nullable=True),
    sa.Column('Saving_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lead_time_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('difficulty_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority_score', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('priority_category', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('Lead_time', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['avocarbon_site.id_site'], name=op.f('fk_opportunity_plant_id_avocarbon_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier_unit.id_supplier_unit'], name=op.f('fk_opportunity_supplier_id_supplier_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', name=op.f('pk_opportunity'))
    )
    op.create_table('supplier_certification',
    sa.Column('id_certification', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_supplier_unit', sa.Integer(), nullable=True),
    sa.Column('certification_type', sa.String(length=100), nullable=True),
    sa.Column('certificate_name', sa.String(length=150), nullable=True),
    sa.Column('amount_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_currency', sa.String(length=10), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('expiry_mode', sa.String(length=30), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_supplier_unit'], ['supplier_unit.id_supplier_unit'], name=op.f('fk_supplier_certification_id_supplier_unit_supplier_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_certification', name=op.f('pk_supplier_certification'))
    )
    op.create_table('supplier_site_relation',
    sa.Column('id_relation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_site', sa.Integer(), nullable=False),
    sa.Column('id_supplier_unit', sa.Integer(), nullable=False),
    sa.Column('alias_1', sa.String(length=200), nullable=True),
    sa.Column('buyer_owner', sa.String(length=200), nullable=True),
    sa.Column('supplier_status', sa.String(length=10), nullable=True),
    sa.Column('operational_grade', sa.CHAR(length=1), nullable=True),
    sa.Column('class_value', sa.Integer(), nullable=True),
    sa.Column('global_status', sa.String(length=50), nullable=True),
    sa.Column('evaluation_frequency', sa.String(length=50), nullable=True),
    sa.Column('last_evaluation_date', sa.Date(), nullable=True),
    sa.Column('next_evaluation_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_site'], ['avocarbon_site.id_site'], name=op.f('fk_supplier_site_relation_id_site_avocarbon_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_supplier_unit'], ['supplier_unit.id_supplier_unit'], name=op.f('fk_supplier_site_relation_id_supplier_unit_supplier_unit'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_relation', name=op.f('pk_supplier_site_relation'))
    )
    op.create_table('contact_site_relation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_contact', sa.Integer(), nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_contact'], ['contact.id_contact'], name=op.f('fk_contact_site_relation_id_contact_contact'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_contact_site_relation_id_relation_supplier_site_relation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_site_relation')),
    sa.UniqueConstraint('id_contact', 'id_relation', name='contact_site_relation_id_contact_id_relation_key')
    )
    op.create_table('document',
    sa.Column('id_document', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('id_supplier_unit', sa.Integer(), nullable=True),
    sa.Column('id_group', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('uploaded_by', sa.String(length=200), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Uploaded', nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_group'], ['supplier_group.id_group'], name=op.f('fk_document_id_group_supplier_group'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_document_id_relation_supplier_site_relation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_supplier_unit'], ['supplier_unit.id_supplier_unit'], name=op.f('fk_document_id_supplier_unit_supplier_unit'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_document', name=op.f('pk_document'))
    )
    op.create_index('idx_document_relation', 'document', ['id_relation'], unique=False)
    op.create_table('evaluation_cycle',
    sa.Column('id_cycle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=False),
    sa.Column('cycle_type', sa.String(length=100), nullable=False),
    sa.Column('supplier_type', sa.String(length=50), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('cycle_status', sa.String(length=50), server_default='Draft', nullable=False),
    sa.Column('launched_by', sa.String(length=200), nullable=True),
    sa.Column('launched_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_evaluation_cycle_id_relation_supplier_site_relation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cycle', name=op.f('pk_evaluation_cycle'))
    )
    op.create_index('idx_evaluation_cycle_relation', 'evaluation_cycle', ['id_relation'], unique=False)
    op.create_table('project',
    sa.Column('project_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=True),
    sa.Column('project_name', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=255), nullable=True),
    sa.Column('project_owner', sa.String(length=255), nullable=True),
    sa.Column('phase_status', sa.String(length=255), nullable=True),
    sa.Column('gate_decision', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('planned_end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('plant_validation', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], name=op.f('fk_project_opportunity_id_opportunity'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project'))
    )
    op.create_table('supplier_agreement',
    sa.Column('id_agreement', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('agreement_type', sa.String(length=50), nullable=True),
    sa.Column('agreement_name', sa.String(length=255), nullable=True),
    sa.Column('amount_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('amount_currency', sa.String(length=10), nullable=True),
    sa.Column('location_value', sa.String(length=150), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('value_unit', sa.String(length=10), nullable=True),
    sa.Column('agreement_description', sa.String(), nullable=True),
    sa.Column('agreement_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_supplier_agreement_id_relation_supplier_site_relation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_agreement', name=op.f('pk_supplier_agreement'))
    )
    op.create_table('supplier_status_history',
    sa.Column('id_history', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('old_class', sa.Integer(), nullable=True),
    sa.Column('new_class', sa.Integer(), nullable=True),
    sa.Column('old_grade', sa.CHAR(length=1), nullable=True),
    sa.Column('new_grade', sa.CHAR(length=1), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_supplier_status_history_id_relation_supplier_site_relation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_history', name=op.f('pk_supplier_status_history'))
    )
    op.create_table('approval_workflow',
    sa.Column('id_approval', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('approval_step', sa.Integer(), nullable=False),
    sa.Column('approver_role', sa.String(length=150), nullable=True),
    sa.Column('approver_name', sa.String(length=200), nullable=True),
    sa.Column('approver_email', sa.String(length=200), nullable=True),
    sa.Column('decision', sa.String(length=50), server_default='Pending', nullable=False),
    sa.Column('decision_date', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_approval_workflow_id_cycle_evaluation_cycle'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_approval', name=op.f('pk_approval_workflow'))
    )
    op.create_index('idx_approval_cycle', 'approval_workflow', ['id_cycle'], unique=False)
    op.create_table('assessment_template',
    sa.Column('id_template', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_type', sa.String(length=100), server_default='SELF_ASSESSMENT', nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Active', nullable=False),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_assessment_template_id_document_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_template', name=op.f('pk_assessment_template'))
    )
    op.create_table('classification',
    sa.Column('id_classification', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('classification_date', sa.Date(), nullable=True),
    sa.Column('classification_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('class_value', sa.Integer(), nullable=True),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('entered_by', sa.String(length=200), nullable=True),
    sa.Column('entered_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_classification_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_classification_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_classification_id_relation_supplier_site_relation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_classification', name=op.f('pk_classification'))
    )
    op.create_table('escalation',
    sa.Column('id_escalation', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=True),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=False),
    sa.Column('escalated_by', sa.String(length=200), nullable=True),
    sa.Column('escalated_to_role', sa.String(length=150), nullable=True),
    sa.Column('escalated_to_name', sa.String(length=200), nullable=True),
    sa.Column('escalation_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Open', nullable=False),
    sa.Column('resolution_comment', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_escalation_id_cycle_evaluation_cycle'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_escalation', name=op.f('pk_escalation'))
    )
    op.create_index('idx_escalation_cycle', 'escalation', ['id_cycle'], unique=False)
    op.create_table('financial_line',
    sa.Column('financial_line_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('line_name', sa.Text(), nullable=True),
    sa.Column('budget_status', sa.String(length=255), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('budget_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('real_start_date', sa.Date(), nullable=True),
    sa.Column('duration_months', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('cumulated_real_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('delta_vs_expected_ytd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('delta_vs_budget_ytd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('follower', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('forecast_eoy_current', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('forecast_eoy_last_update', sa.Date(), nullable=True),
    sa.Column('expected_annual_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunity.opportunity_id'], name=op.f('fk_financial_line_opportunity_id_opportunity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['avocarbon_site.id_site'], name=op.f('fk_financial_line_plant_id_avocarbon_site'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], name=op.f('fk_financial_line_project_id_project'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('financial_line_id', name=op.f('pk_financial_line'))
    )
    op.create_table('input_delivery_spend',
    sa.Column('id_delivery_spend', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('part_reference', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('purchase_price_delivery', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('supplier_id', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('bad_parts', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('plant', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_input_delivery_spend_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_input_delivery_spend_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_input_delivery_spend_id_relation_supplier_site_relation'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_delivery_spend', name=op.f('pk_input_delivery_spend'))
    )
    op.create_index('idx_input_delivery_spend_cycle', 'input_delivery_spend', ['id_cycle'], unique=False)
    op.create_table('input_otd_monthly',
    sa.Column('id_otd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('month_date', sa.Date(), nullable=True),
    sa.Column('otd_raw_value', sa.String(length=50), nullable=True),
    sa.Column('otd_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('plant', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_input_otd_monthly_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_input_otd_monthly_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_input_otd_monthly_id_relation_supplier_site_relation'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_otd', name=op.f('pk_input_otd_monthly'))
    )
    op.create_index('idx_input_otd_monthly_cycle', 'input_otd_monthly', ['id_cycle'], unique=False)
    op.create_table('input_quality_claims',
    sa.Column('id_quality_claim', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('claimed_part_reference', sa.String(length=150), nullable=True),
    sa.Column('claim_number', sa.String(length=150), nullable=True),
    sa.Column('claim_opening_date', sa.Date(), nullable=True),
    sa.Column('claim_closing_date', sa.Date(), nullable=True),
    sa.Column('claim_status', sa.String(length=50), nullable=True),
    sa.Column('supplier_id', sa.String(length=100), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('plant', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_input_quality_claims_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_input_quality_claims_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_input_quality_claims_id_relation_supplier_site_relation'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_quality_claim', name=op.f('pk_input_quality_claims'))
    )
    op.create_index('idx_input_quality_claims_cycle', 'input_quality_claims', ['id_cycle'], unique=False)
    op.create_table('score_card',
    sa.Column('id_score_card', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('scorecard_date', sa.Date(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('grade', sa.CHAR(length=1), nullable=True),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('entered_by', sa.String(length=200), nullable=True),
    sa.Column('entered_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_score_card_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_score_card_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_score_card_id_relation_supplier_site_relation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_score_card', name=op.f('pk_score_card'))
    )
    op.create_table('scorecard_data_quality_checks',
    sa.Column('id_check', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('dataset', sa.String(length=150), nullable=False),
    sa.Column('check_name', sa.String(length=200), nullable=False),
    sa.Column('check_description', sa.Text(), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('target_operator', sa.String(length=10), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('check_status', sa.String(length=50), nullable=True),
    sa.Column('formula_reference', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_scorecard_data_quality_checks_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_scorecard_data_quality_checks_id_document_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_check', name=op.f('pk_scorecard_data_quality_checks'))
    )
    op.create_table('scorecard_upload_register',
    sa.Column('id_upload_register', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('reporting_period', sa.String(length=50), nullable=True),
    sa.Column('plant', sa.String(length=150), nullable=True),
    sa.Column('dataset', sa.String(length=150), nullable=True),
    sa.Column('owner_function', sa.String(length=150), nullable=True),
    sa.Column('contact', sa.String(length=200), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('upload_date', sa.Date(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('validation_status', sa.String(length=50), server_default='Pending', nullable=False),
    sa.Column('plant_approval', sa.String(length=50), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timeliness_flag', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_scorecard_upload_register_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_scorecard_upload_register_id_document_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_upload_register', name=op.f('pk_scorecard_upload_register'))
    )
    op.create_table('assessment_template_field_mapping',
    sa.Column('id_mapping', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_template', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=150), nullable=False),
    sa.Column('field_code', sa.String(length=150), nullable=False),
    sa.Column('field_label', sa.String(length=255), nullable=True),
    sa.Column('cell_reference', sa.String(length=50), nullable=True),
    sa.Column('column_reference', sa.String(length=50), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=True),
    sa.Column('target_table', sa.String(length=150), nullable=True),
    sa.Column('target_column', sa.String(length=150), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_template'], ['assessment_template.id_template'], name=op.f('fk_assessment_template_field_mapping_id_template_assessment_template'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mapping', name=op.f('pk_assessment_template_field_mapping'))
    )
    op.create_table('monthly_financial',
    sa.Column('monthly_financial_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('financial_line_id', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=True),
    sa.Column('expected_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('actual_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cumulated_expected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cumulated_actual', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('delta_vs_expected', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('delta_vs_budget', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('forecast_eoy_saving', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('forecast_comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['financial_line_id'], ['financial_line.financial_line_id'], name=op.f('fk_monthly_financial_financial_line_id_financial_line'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('monthly_financial_id', name=op.f('pk_monthly_financial'))
    )
    op.create_table('scorecard_kpi_detail',
    sa.Column('id_kpi_detail', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_score_card', sa.Integer(), nullable=True),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('kpi_name', sa.String(length=150), nullable=False),
    sa.Column('kpi_category', sa.String(length=100), nullable=True),
    sa.Column('kpi_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('kpi_unit', sa.String(length=50), nullable=True),
    sa.Column('kpi_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('weighted_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_dataset', sa.String(length=150), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_scorecard_kpi_detail_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_scorecard_kpi_detail_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_scorecard_kpi_detail_id_relation_supplier_site_relation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_score_card'], ['score_card.id_score_card'], name=op.f('fk_scorecard_kpi_detail_id_score_card_score_card'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_kpi_detail', name=op.f('pk_scorecard_kpi_detail'))
    )
    op.create_index('idx_scorecard_kpi_cycle', 'scorecard_kpi_detail', ['id_cycle'], unique=False)
    op.create_table('supplier_assessment',
    sa.Column('id_assessment', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_relation', sa.Integer(), nullable=True),
    sa.Column('id_template', sa.Integer(), nullable=True),
    sa.Column('id_document', sa.Integer(), nullable=True),
    sa.Column('id_cycle', sa.Integer(), nullable=True),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='Received', nullable=False),
    sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('final_grade', sa.CHAR(length=1), nullable=True),
    sa.Column('final_class', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cycle'], ['evaluation_cycle.id_cycle'], name=op.f('fk_supplier_assessment_id_cycle_evaluation_cycle'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_document'], ['document.id_document'], name=op.f('fk_supplier_assessment_id_document_document'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_relation'], ['supplier_site_relation.id_relation'], name=op.f('fk_supplier_assessment_id_relation_supplier_site_relation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_template'], ['assessment_template.id_template'], name=op.f('fk_supplier_assessment_id_template_assessment_template'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_assessment', name=op.f('pk_supplier_assessment'))
    )
    op.create_table('supplier_assessment_answer',
    sa.Column('id_answer', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_assessment', sa.Integer(), nullable=False),
    sa.Column('id_mapping', sa.Integer(), nullable=True),
    sa.Column('field_code', sa.String(length=150), nullable=True),
    sa.Column('field_label', sa.String(length=255), nullable=True),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('validation_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_assessment'], ['supplier_assessment.id_assessment'], name=op.f('fk_supplier_assessment_answer_id_assessment_supplier_assessment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_mapping'], ['assessment_template_field_mapping.id_mapping'], name=op.f('fk_supplier_assessment_answer_id_mapping_assessment_template_field_mapping'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_answer', name=op.f('pk_supplier_assessment_answer'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_assessment_answer')
    op.drop_table('supplier_assessment')
    op.drop_index('idx_scorecard_kpi_cycle', table_name='scorecard_kpi_detail')
    op.drop_table('scorecard_kpi_detail')
    op.drop_table('monthly_financial')
    op.drop_table('assessment_template_field_mapping')
    op.drop_table('scorecard_upload_register')
    op.drop_table('scorecard_data_quality_checks')
    op.drop_table('score_card')
    op.drop_index('idx_input_quality_claims_cycle', table_name='input_quality_claims')
    op.drop_table('input_quality_claims')
    op.drop_index('idx_input_otd_monthly_cycle', table_name='input_otd_monthly')
    op.drop_table('input_otd_monthly')
    op.drop_index('idx_input_delivery_spend_cycle', table_name='input_delivery_spend')
    op.drop_table('input_delivery_spend')
    op.drop_table('financial_line')
    op.drop_index('idx_escalation_cycle', table_name='escalation')
    op.drop_table('escalation')
    op.drop_table('classification')
    op.drop_table('assessment_template')
    op.drop_index('idx_approval_cycle', table_name='approval_workflow')
    op.drop_table('approval_workflow')
    op.drop_table('supplier_status_history')
    op.drop_table('supplier_agreement')
    op.drop_table('project')
    op.drop_index('idx_evaluation_cycle_relation', table_name='evaluation_cycle')
    op.drop_table('evaluation_cycle')
    op.drop_index('idx_document_relation', table_name='document')
    op.drop_table('document')
    op.drop_table('contact_site_relation')
    op.drop_table('supplier_site_relation')
    op.drop_table('supplier_certification')
    op.drop_table('opportunity')
    op.drop_table('contact')
    op.drop_table('supplier_unit')
    op.drop_table('supplier_group')
    op.drop_table('pld_scoring_rules')
    op.drop_table('avocarbon_site')
    # ### end Alembic commands ###
